version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/pipeline_aws/
permissions:
  - object: /var/www/html/pipeline_aws
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
